/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EmprestimoDAO;
import dao.MultaDAO;
import dao.UsuarioDAO;
import entities.Emprestimo;
import entities.Multa;
import entities.Usuario;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import utils.Data;

/**
 *
 * @author Gustavo Martini
 */
public class DlgPagarMultas extends javax.swing.JDialog {

    MultaDAO multaDAO = new MultaDAO();
    int cod_usuario = 0;
    long diasAtrasados = 0;
    double valorTotal = 0;
    int cod_multa = 0;

    /**
     * Creates new form DlgGerenciarMultas
     */
    public DlgPagarMultas(java.awt.Frame parent, boolean modal, int cod_usuario) {
        super(parent, modal);
        initComponents();
        setTitle("Pagar multa");
        setLocationRelativeTo(parent);
        setResizable(false);
        this.cod_usuario = cod_usuario;

        Usuario usuario = new UsuarioDAO().consultarId(cod_usuario);
        String usuarioInfo = usuario.getId() + " - " + usuario.getNome() + " " + usuario.getSobrenome();
        lblUsuario.setText(usuarioInfo);

        multaDAO.popularTabela(tblMultas, cod_usuario + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfDiasAtrasados = new javax.swing.JTextField();
        ftfTaxaDiaria = new javax.swing.JFormattedTextField();
        ftfValorTotal = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblUsuario.setText("usuario");

        jLabel1.setText("Dias de atraso:");

        btnCancelar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/close.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPagar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/money.png")); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel2.setText("Taxa diária:");

        jLabel3.setText("Valor total:");

        txfDiasAtrasados.setEditable(false);

        ftfTaxaDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        ftfTaxaDiaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftfTaxaDiariaKeyReleased(evt);
            }
        });

        ftfValorTotal.setEditable(false);
        ftfValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Valor", "Pago", "Data Pgto", "Cód. Empréstimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMultas.getTableHeader().setReorderingAllowed(false);
        tblMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMultas);
        if (tblMultas.getColumnModel().getColumnCount() > 0) {
            tblMultas.getColumnModel().getColumn(0).setMinWidth(50);
            tblMultas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblMultas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel4.setText("Lista de multas do usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addComponent(txfDiasAtrasados)
                            .addComponent(ftfTaxaDiaria)
                            .addComponent(ftfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsuario)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfDiasAtrasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftfTaxaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnPagar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {

            String retorno = "";

            Multa multa = multaDAO.consultarId(cod_multa);
            multa.setPago(true);
            multa.setValor(valorTotal);
            multa.setData_pgto(Data.dateToString(Data.dataAtual()));

            if (valorTotal == 0.00) {
                JOptionPane.showMessageDialog(null, "Informe a taxa diária de multa.");
                ftfTaxaDiaria.requestFocus();
                return;
            }
            
            retorno = multaDAO.atualizar(multa);
            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Multa paga com sucesso!");

                multaDAO.popularTabela(tblMultas, cod_usuario + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao pagar multa.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void ftfTaxaDiariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfTaxaDiariaKeyReleased
        try {
            double taxaDiaria = ftfTaxaDiaria.getText().equals("")
                    ? 0.00 : Double.parseDouble(ftfTaxaDiaria.getText());
            
            valorTotal = taxaDiaria * diasAtrasados;
            DecimalFormat df = new DecimalFormat("####0.00");
            ftfValorTotal.setText("R$" + df.format(valorTotal) + "");

        } catch (Exception e) {
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_ftfTaxaDiariaKeyReleased

    private void tblMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMultasMouseClicked
        try {
            String isPago = String.valueOf(tblMultas.getValueAt(tblMultas.getSelectedRow(), 2));
            if (isPago.equals("Pago")) {
                JOptionPane.showMessageDialog(null, "A multa selecionada já está paga!");
                return;
            }
            
            String idString = String.valueOf(tblMultas.getValueAt(tblMultas.getSelectedRow(), 0));
            cod_multa = Integer.parseInt(idString);

            String cod_empString = String.valueOf(tblMultas.getValueAt(tblMultas.getSelectedRow(), 4));
            int cod_emprestimo = Integer.parseInt(cod_empString);

            Emprestimo emprestimo = new EmprestimoDAO().consultarId(cod_emprestimo);

            diasAtrasados = Data.compareDates(
                    Data.stringToDate(emprestimo.getData_devolucao()),
//                    Data.dataAtual()
                    Data.stringToDate(emprestimo.getData_devolvido())
            );
            
            txfDiasAtrasados.setText(diasAtrasados + " dia(s)");
        } catch (Exception e) {
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_tblMultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPagarMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPagarMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPagarMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPagarMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPagarMultas dialog = new DlgPagarMultas(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JFormattedTextField ftfTaxaDiaria;
    private javax.swing.JFormattedTextField ftfValorTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblMultas;
    private javax.swing.JTextField txfDiasAtrasados;
    // End of variables declaration//GEN-END:variables
}
