/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EmprestimoDAO;
import dao.EmprestimoExemplarDAO;
import dao.ExemplarDAO;
import dao.LivroDAO;
import dao.MultaDAO;
import dao.PerfilDAO;
import dao.UsuarioDAO;
import entities.Emprestimo;
import entities.Exemplar;
import entities.Multa;
import entities.Perfil;
import entities.Usuario;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utils.Data;

/**
 *
 * @author Gustavo Martini
 */
public class IfrEmprestimoDevolucao extends javax.swing.JInternalFrame {

    int cod_usuario = 0;
    int cod_emprestimoPendente = 0;
    int prazo = 0;
    boolean atrasado = false;
    boolean podeRenovar = true;
    boolean pendente = false;

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    LivroDAO livroDAO = new LivroDAO();
    PerfilDAO perfilDAO = new PerfilDAO();
    EmprestimoDAO emprestimoDAO = new EmprestimoDAO();
    EmprestimoExemplarDAO emprestimoExemplarDAO = new EmprestimoExemplarDAO();
    MultaDAO multaDAO = new MultaDAO();
    ArrayList<Emprestimo> emprestimos = new ArrayList<>();
    Perfil perfil = null;
    Usuario usuario = null;
    Emprestimo emprestimo = null;

    /**
     * Creates new form IfrEmprestimo
     */
    public IfrEmprestimoDevolucao() {
        initComponents();
        setTitle("Devolver ou Renovar Empréstimo");
        setClosable(true);

        limparTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnMultas = new javax.swing.JButton();
        btnEmprestimoInfos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        btnRenovar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblUsuarioNome = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txfCod = new javax.swing.JTextField();
        txfDataDevolucao = new javax.swing.JTextField();
        txfAtrasado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfMultaPendente = new javax.swing.JTextField();

        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/loupe.png")); // NOI18N
        btnBuscarUsuario.setText("Buscar Usuário");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Data Retirada", "Data Devolução", "Renovações", "Devolvido", "Usuário", "Funcionário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEmprestimos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmprestimos);
        if (tblEmprestimos.getColumnModel().getColumnCount() > 0) {
            tblEmprestimos.getColumnModel().getColumn(0).setMinWidth(50);
            tblEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblEmprestimos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel2.setText("Empréstimos:");

        btnMultas.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/money.png")); // NOI18N
        btnMultas.setText("Multas");
        btnMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasActionPerformed(evt);
            }
        });

        btnEmprestimoInfos.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/info.png")); // NOI18N
        btnEmprestimoInfos.setText("Informações do empréstimo");
        btnEmprestimoInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoInfosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Empréstimo pendente");

        btnDevolver.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/return.png")); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnRenovar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/renew.png")); // NOI18N
        btnRenovar.setText("Renovar");
        btnRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/close.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblUsuarioNome.setText(" ");

        btnLimpar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/clean.png")); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel4.setText("Cód.:");

        jLabel5.setText("Data para devolução:");

        jLabel6.setText("Empréstimo Atrasado:");

        txfCod.setEditable(false);

        txfDataDevolucao.setEditable(false);

        txfAtrasado.setEditable(false);
        txfAtrasado.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jLabel1.setText("Multa pendente:");

        txfMultaPendente.setEditable(false);
        txfMultaPendente.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(btnEmprestimoInfos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuarioNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMultas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfCod, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txfDataDevolucao)
                            .addComponent(txfAtrasado)
                            .addComponent(txfMultaPendente))
                        .addGap(255, 255, 255)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRenovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarUsuario)
                            .addComponent(lblUsuarioNome))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMultas)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmprestimoInfos)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenovar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txfAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfMultaPendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparTela() {
        lblUsuarioNome.setText("");
        txfAtrasado.setText("");
        txfCod.setText("");
        txfDataDevolucao.setText("");
        emprestimoDAO.popularTabela(tblEmprestimos, 0, "", "");
        cod_usuario = 0;

        btnMultas.setEnabled(false);
        btnRenovar.setEnabled(false);
        btnDevolver.setEnabled(false);
    }

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        Frame parentFrame = (Frame) SwingUtilities.getAncestorOfClass(Window.class, this);
        DlgBuscaUsuario dlgBuscaUsuario = new DlgBuscaUsuario(parentFrame, true);
        dlgBuscaUsuario.setVisible(true);

        try {
            txfAtrasado.setText("");
            txfCod.setText("");
            txfDataDevolucao.setText("");
            emprestimo = null;
            podeRenovar = true;
            atrasado = false;
            cod_emprestimoPendente = 0;

            cod_usuario = dlgBuscaUsuario.cod_usuario;
            usuario = usuarioDAO.consultarId(cod_usuario);
            emprestimos = emprestimoDAO.consultar(cod_usuario + "");
            perfil = perfilDAO.consultarId(usuario.getCod_perfil());
            prazo = perfil.getPrazo();

            emprestimoDAO.popularTabela(tblEmprestimos, cod_usuario, "", "devolvido");

            if (cod_usuario != 0) {
                btnMultas.setEnabled(true);
            } else {
                btnMultas.setEnabled(false);
            }

            pendente = multaDAO.consultar(cod_usuario);

            if (pendente) {
                txfMultaPendente.setText("Sim");
                txfMultaPendente.setForeground(Color.RED);
            } else {
                txfMultaPendente.setText("Não");
                txfMultaPendente.setForeground(Color.BLACK);
            }
            

            if (emprestimos.size() > 0) {
                for (Emprestimo emp : emprestimos) {
                    if (emp.isDevolvido() == false) {
                        emprestimo = emp;
                        cod_emprestimoPendente = emp.getId();

                    }
                }

                if (cod_emprestimoPendente == 0) {
                    btnDevolver.setEnabled(false);
                } else {
                    btnDevolver.setEnabled(true);
                }

                if (emprestimo != null) {
                    if (emprestimo.getRenovacoes() < perfil.getQtde_renovacoes()) {
                        System.out.println("renovacoes emprestimo" + emprestimo.getRenovacoes());
                        System.out.println("renovacoes perfil" + perfil.getQtde_renovacoes());
                        btnRenovar.setEnabled(true);
                    }

                    txfCod.setText(emprestimo.getId() + "");

                    long diferenca_datas = Data.compareDates(Data.dataAtual(), Data.stringToDate(emprestimo.getData_devolucao()));

                    txfDataDevolucao.setText(emprestimo.getData_devolucao());
                    atrasado = diferenca_datas < 0;

                    String lblAtrasadoString = atrasado ? "Sim" : "Não";
                    txfAtrasado.setText(lblAtrasadoString);
                    txfAtrasado.setForeground(atrasado ? Color.RED : Color.BLACK);
                    if (atrasado) {
                        btnRenovar.setEnabled(false);
                    }
                }
            }
            lblUsuarioNome.setText(usuario.getId() + " - " + usuario.getNome() + " " + usuario.getSobrenome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado!");
            System.err.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEmprestimoInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoInfosActionPerformed
        try {
            String idString = String.valueOf(tblEmprestimos.getValueAt(tblEmprestimos.getSelectedRow(), 0));
            int cod_emprestimo = Integer.parseInt(idString);

            Frame parentFrame = (Frame) SwingUtilities.getAncestorOfClass(Window.class, this);
            DlgEmprestimoInfos dlgEmprestimoInfos = new DlgEmprestimoInfos(parentFrame, true, cod_emprestimo, cod_usuario);
            dlgEmprestimoInfos.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum empréstimo selecionado.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnEmprestimoInfosActionPerformed

    private void btnRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarActionPerformed
        try {
            if (atrasado) {
                JOptionPane.showMessageDialog(null, "Empréstimo atrasado não pode ser renovado!");
                return;
            }

            String retorno = "";

            int qtdeRenovacoesDisponiveis = perfil.getQtde_renovacoes() - emprestimo.getRenovacoes();

            if (qtdeRenovacoesDisponiveis <= 0) {
                JOptionPane.showMessageDialog(null, "Este empréstimo já atingiu o limite de renovações!");
                return;
            }

            Date data_devolucaoDate = Data.stringToDate(emprestimo.getData_devolucao());

            Date novaDataDevolucaoDate = Data.somarDia(data_devolucaoDate, prazo);
            String novaDataDevolucao = Data.dateToString(novaDataDevolucaoDate);

            int renovacoesAtualizada = emprestimo.getRenovacoes() + 1;

            emprestimo.setRenovacoes(renovacoesAtualizada);
            emprestimo.setData_devolucao(novaDataDevolucao);

            retorno = emprestimoDAO.atualizar(emprestimo);

            if (retorno == null) {
                txfDataDevolucao.setText(emprestimo.getData_devolucao());
                JOptionPane.showMessageDialog(null, "Empréstimo renovado com sucesso.");

                emprestimoDAO.popularTabela(tblEmprestimos, cod_usuario, "", "devolvido");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao renovar empréstimo.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnRenovarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        try {

            String retorno = "";

            // se estiver atrasado, abrir janela para pagar multa
            if (atrasado) {
                Multa multa = new Multa();
                multa.setEmprestimo(emprestimo);
                retorno = multaDAO.salvar(multa);
            }

            // atualizar emprestimo_exemplar
            ArrayList<Exemplar> exemplares = new ArrayList<>();
            exemplares = new EmprestimoExemplarDAO().consultar(cod_emprestimoPendente + "");

            for (Exemplar ex : exemplares) {
                ex.setCod_estado(1);
                retorno = new ExemplarDAO().atualizar(ex);
            }

            // realizar a devolucao do emprestimo
            if (retorno == null) {
                retorno = emprestimoDAO.excluir(cod_emprestimoPendente);
            }

            // retornar msg de sucesso
            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Empréstimo devolvido com sucesso.");

                emprestimoDAO.popularTabela(tblEmprestimos, cod_usuario, "", "");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao devolver empréstimo.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasActionPerformed
        try {
            Frame parentFrame = (Frame) SwingUtilities.getAncestorOfClass(Window.class, this);
            DlgPagarMultas dlgGerenciarMultas = new DlgPagarMultas(parentFrame, true, cod_usuario);
            dlgGerenciarMultas.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao abrir multas.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnMultasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEmprestimoInfos;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMultas;
    private javax.swing.JButton btnRenovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblUsuarioNome;
    private javax.swing.JTable tblEmprestimos;
    private javax.swing.JTextField txfAtrasado;
    private javax.swing.JTextField txfCod;
    private javax.swing.JTextField txfDataDevolucao;
    private javax.swing.JTextField txfMultaPendente;
    // End of variables declaration//GEN-END:variables
}
