/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CombosDAO;
import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import entities.Usuario;
import java.awt.Color;
import utils.ComboItem;
import utils.EmailValidator;
import utils.Validacao;

/**
 *
 * @author gustavo
 */
public class IfrUsuario extends javax.swing.JInternalFrame {

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    Usuario usuario;
    int id = 0;

    /**
     * Creates new form IfrUsuario
     */
    public IfrUsuario() {
        initComponents();
        setTitle("Usuário");
        setClosable(true);

        new CombosDAO().popularCombo("perfil", "cod_perfil", "perfil", cbxPerfil, "WHERE situacao = 'ativo'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpUsuario = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        txfSobrenome = new javax.swing.JTextField();
        txfEndereco = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txfCPF = new javax.swing.JFormattedTextField();
        txfDataNasc = new javax.swing.JFormattedTextField();
        txfTelefone = new javax.swing.JFormattedTextField();
        cbxSituacao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hglCPF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxPerfil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pnlConsulta = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblCriterio = new javax.swing.JLabel();
        txfBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        tbpUsuario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpUsuarioStateChanged(evt);
            }
        });

        lblNome.setText("Nome:");

        lblSobrenome.setText("Sobrenome:");

        lblEndereco.setText("Endereço:");

        lblCPF.setText("CPF:");

        lblEmail.setText("E-mail:");

        lblDataNasc.setText("Data de Nascimento:");

        lblTelefone.setText("Telefone:");

        lblSituacao.setText("Situação:");

        txfNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfNomeMouseClicked(evt);
            }
        });

        txfSobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfSobrenomeMouseClicked(evt);
            }
        });

        txfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfEmailMouseClicked(evt);
            }
        });

        try {
            txfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfCPFMouseClicked(evt);
            }
        });

        try {
            txfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfDataNasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfDataNascMouseClicked(evt);
            }
        });

        try {
            txfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfTelefoneMouseClicked(evt);
            }
        });

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jLabel1.setText("* Campo obrigatório");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        hglCPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        hglCPF.setForeground(new java.awt.Color(255, 0, 0));
        hglCPF.setText("*");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setText("Perfil:");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        btnUpdate.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/refresh.png")); // NOI18N
        btnUpdate.setToolTipText("Atualizar Perfis");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblNome))
                                .addGap(30, 30, 30))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblSituacao))
                                .addGap(18, 18, 18)))
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                                        .addComponent(cbxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txfTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addComponent(txfNome, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSobrenome, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEndereco, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                                        .addComponent(hglCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                        .addComponent(lblDataNasc)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfDataNasc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(52, 52, 52))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSobrenome)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF)
                            .addComponent(hglCPF)
                            .addComponent(txfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNasc)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))))
                    .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEndereco)))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSituacao)
                    .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        tbpUsuario.addTab("Cadastro", pnlCadastro);

        lblTipo.setText("Tipo:");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Sobrenome", "CPF" }));

        lblCriterio.setText("Critério:");

        btnBuscar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/loupe.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Nome", "Sobrenome", "Endereço", "CPF", "E-mail", "Data Nasc.", "Telefone", "Perfil", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUsuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsuario);
        if (tblUsuario.getColumnModel().getColumnCount() > 0) {
            tblUsuario.getColumnModel().getColumn(0).setMinWidth(50);
            tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblUsuario.getColumnModel().getColumn(0).setMaxWidth(50);
            tblUsuario.getColumnModel().getColumn(9).setMinWidth(70);
            tblUsuario.getColumnModel().getColumn(9).setPreferredWidth(60);
            tblUsuario.getColumnModel().getColumn(9).setMaxWidth(50);
        }

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCriterio)
                        .addGap(18, 18, 18)
                        .addComponent(txfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCriterio)
                    .addComponent(txfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tbpUsuario.addTab("Consulta", pnlConsulta);

        btnExcluir.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/delete.png")); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/edit.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/floppy-disk.png")); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon("/home/gustavo/NetBeansProjects/Biblioteca/icons/new.png")); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(65, 65, 65))
            .addComponent(tbpUsuario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCadastro() {
        txfCPF.setEnabled(true);
        hglCPF.setVisible(true);

        txfNome.setText("");
        txfSobrenome.setText("");
        txfCPF.setText("");
        txfTelefone.setText("");
        txfEmail.setText("");
        txfDataNasc.setText("");
        txfEndereco.setText("");
        cbxPerfil.setSelectedIndex(0);
        cbxSituacao.setSelectedIndex(0);

        id = 0;

        tbpUsuario.setSelectedIndex(0);

        txfNome.requestFocus();
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCadastro();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String retorno = null;

        String nome = txfNome.getText().trim();
        String sobrenome = txfSobrenome.getText().trim();
        String cpf = txfCPF.getText();
        String telefone = txfTelefone.getText();
        String email = txfEmail.getText().trim();
        String data_nasc = txfDataNasc.getText();
        String endereco = txfEndereco.getText().trim();
        ComboItem ciPerfil = (ComboItem) cbxPerfil.getSelectedItem();
        int cod_perfil = ciPerfil.getCodigo();
        String situacao = cbxSituacao.getSelectedItem().toString().toLowerCase();

        usuario = new Usuario();

        usuario.setId(id);
        usuario.setNome(nome);
        usuario.setSobrenome(sobrenome);
        usuario.setCpf(cpf);
        usuario.setTelefone(telefone);
        usuario.setEmail(email);
        usuario.setData_nasc(data_nasc);
        usuario.setEndereco(endereco);
        usuario.setCod_perfil(cod_perfil);
        usuario.setSituacao(situacao);
        
        // VALIDAÇÃO DE CAMPOS EM BRANCO
        if (nome.isEmpty()
                || sobrenome.isEmpty()
                || cpf.isEmpty()
                || telefone.isEmpty()
                || email.isEmpty()) {
            pnlCadastro.setVisible(true);
            tbpUsuario.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
            return;
        }

        Validacao validar = new Validacao();
        EmailValidator emailVal = new EmailValidator();
        
        // VALIDAÇÃO DE CAMPOS INVÁLIDOS
        if (validar.validarNome(nome) == false
                || validar.validarNome(sobrenome) == false
                || validar.validarCPF(validar.removerFormatacao(cpf)) == false
                || validar.validarDataFormatada(data_nasc) == false
                || emailVal.validate(email) == false) {

            if (validar.validarNome(nome) == false) {
                txfNome.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Digite um nome válido!");
                txfNome.requestFocus();
            }

            if (validar.validarNome(sobrenome) == false) {
                txfSobrenome.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Digite um sobrenome válido!");
                txfSobrenome.requestFocus();
            }
            
            if (validar.validarCPF(validar.removerFormatacao(cpf)) == false) {
                txfCPF.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Digite um CPF válido!");
                txfCPF.requestFocus();
            }
            
            if (validar.validarDataFormatada(data_nasc) == false) {
                txfDataNasc.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Digite uma data de nascimento válida!");
                txfDataNasc.requestFocus();
            }

            if (emailVal.validate(email) == false) {
                txfEmail.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Digite um e-mail válido!");
                txfEmail.requestFocus();
            }

            return;
        }

        // VALIDAÇÃO DE EMAIL E CPF JÁ CADASTRADOS
        if (usuarioDAO.emailExiste(email, id)) {
            txfEmail.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "O endereço de e-mail informado já está cadastrado no sistema!");
            txfEmail.requestFocus();
            return;
        }

        if (usuarioDAO.cpfExiste(cpf, id)) {
            txfCPF.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "O CPF informado já está cadastrado!");
            txfCPF.requestFocus();
            return;
        }
        
        // VALIDAÇÂO CAMPO PERFIL
        if (cbxPerfil.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um perfil para o usuário!"
                    + "\n\n"
                    + "Caso necessário, cadastre um novo perfil!");
            return;
        }

        if (id != 0) {
            retorno = usuarioDAO.atualizar(usuario);
        } else {
            retorno = usuarioDAO.salvar(usuario);
        }

        // APÓS SALVAR/ATUALIZAR, LIMPA OS CAMPOS DO CADASTRO
        if (retorno == null) {
            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");

            limparCadastro();

            usuarioDAO.popularTabela(tblUsuario, txfBusca.getText(), "nome");
        } else {
            JOptionPane.showMessageDialog(null, "Problemas ao salvar usuário!\n\n"
                    + "Mensagem técnica:\n"
                    + "Erro: " + retorno);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String idString = String.valueOf(tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0));

            id = Integer.parseInt(idString);

            usuario = usuarioDAO.consultarId(id);

            tbpUsuario.setSelectedIndex(0);

            txfNome.setText(usuario.getNome());
            txfSobrenome.setText(usuario.getSobrenome());
            txfCPF.setText(usuario.getCpf());
            txfDataNasc.setText(usuario.getData_nasc());
            txfTelefone.setText(usuario.getTelefone());
            txfEndereco.setText(usuario.getEndereco());
            txfEmail.setText(usuario.getEmail());
            ComboItem ciPerfil = new ComboItem();
            ciPerfil.setCodigo(usuario.getCod_perfil());
            new CombosDAO().definirItemCombo(cbxPerfil, ciPerfil);

            if (usuario.getSituacao().equals("ativo")) {
                cbxSituacao.setSelectedIndex(0);
            } else if (usuario.getSituacao().equals("inativo")) {
                cbxSituacao.setSelectedIndex(1);
            }

            txfCPF.setEnabled(false);
            hglCPF.setVisible(false);
            txfNome.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            usuario = new Usuario();

            String idString = String.valueOf(tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0));
            id = Integer.parseInt(idString);

            usuario = usuarioDAO.consultarId(id);

            if (usuario.getSituacao().equals("inativo")) {
                JOptionPane.showMessageDialog(null, "Este registro já está inativo!");
            } else {
                int opcao = JOptionPane.showConfirmDialog(null, "Desejar realmente excluir?");

                System.out.println("Opção = " + opcao);

                if (opcao == JOptionPane.OK_OPTION) {

                    String retorno = usuarioDAO.excluir(id);

                    if (retorno == null) {
                        JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                        usuarioDAO.popularTabela(tblUsuario, "", "nome");
                    } else {
                        JOptionPane.showMessageDialog(null, "Ops, problemas ao excluir registro.");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado.");
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (cbxTipo.getSelectedItem().toString().equals("Nome")) {
            usuarioDAO.popularTabela(tblUsuario, txfBusca.getText(), "nome");
        } else if (cbxTipo.getSelectedItem().toString().equals("Sobrenome")) {
            usuarioDAO.popularTabela(tblUsuario, txfBusca.getText(), "sobrenome");
        } else if (cbxTipo.getSelectedItem().toString().equals("CPF")) {
            usuarioDAO.popularTabela(tblUsuario, txfBusca.getText(), "cpf");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        new CombosDAO().popularCombo("perfil", "cod_perfil", "perfil", cbxPerfil, "WHERE situacao = 'ativo'");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbpUsuarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpUsuarioStateChanged
        btnExcluir.setEnabled(false);

        if (tbpUsuario.getSelectedIndex() == 1) {
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tbpUsuarioStateChanged

    private void txfNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfNomeMouseClicked
        txfNome.setForeground(Color.black);
    }//GEN-LAST:event_txfNomeMouseClicked

    private void txfSobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfSobrenomeMouseClicked
        txfSobrenome.setForeground(Color.black);
    }//GEN-LAST:event_txfSobrenomeMouseClicked

    private void txfCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfCPFMouseClicked
        txfCPF.setForeground(Color.black);
    }//GEN-LAST:event_txfCPFMouseClicked

    private void txfDataNascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfDataNascMouseClicked
        txfDataNasc.setForeground(Color.black);
    }//GEN-LAST:event_txfDataNascMouseClicked

    private void txfTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfTelefoneMouseClicked
        txfTelefone.setForeground(Color.black);
    }//GEN-LAST:event_txfTelefoneMouseClicked

    private void txfEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfEmailMouseClicked
        txfEmail.setForeground(Color.black);
    }//GEN-LAST:event_txfEmailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxPerfil;
    private javax.swing.JComboBox<String> cbxSituacao;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel hglCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCriterio;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTabbedPane tbpUsuario;
    private javax.swing.JTextField txfBusca;
    private javax.swing.JFormattedTextField txfCPF;
    private javax.swing.JFormattedTextField txfDataNasc;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEndereco;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfSobrenome;
    private javax.swing.JFormattedTextField txfTelefone;
    // End of variables declaration//GEN-END:variables
}
